version: "3.8"

services:
  db:
    image: mysql:8
    container_name: blog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: blog
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: blog-backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: bloguser
      DB_PASSWORD: blogpass
      DB_NAME: blog
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
