version: "3.8"
services:
  backend:
    build: ./backend
    container_name: simple-market-backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    container_name: simple-market-frontend
    ports:
      - "8080:80"
  nginx:
    image: nginx:alpine
    container_name: simple-market-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
