version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: med_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: medical
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: med_backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=meduser
      - DB_PASSWORD=medpass
      - DB_NAME=medical
    depends_on:
      db:
         condition: service_healthy
        
