events { }

http {
    upstream frontend_cluster {
        server 192.168.107.196:8080;  # VM1 frontend
        server 192.168.107.197:8080;  # VM2 frontend
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_cluster;
        }
    }
}

